"""
generate_oauth2_token.py
=====================================
Generates a YouTube OAuth2 token using pytubefix and formats
it ready to paste into Render as the YT_OAUTH2_TOKEN environment variable.

Run this ONCE on your PC:
    .\venv\Scripts\python.exe generate_oauth2_token.py

Requirements:
- pytubefix must be installed (it is in the bot's venv)
"""

import sys
import os
import base64
import json

def main():
    print("=================================================================")
    print("  YouTube OAuth2 Token Generator for Bot-Guard Bypass")
    print("=================================================================\n")

    try:
        import pytubefix
        from pytubefix import YouTube
        import pytubefix.innertube
        
        # Override cache_dir to a local writable folder to match downloader.py
        cache_dir = os.path.join(os.path.abspath(os.path.dirname(__file__)), 'bot_temp', 'pytubefix_cache')
        os.makedirs(cache_dir, exist_ok=True)
        pytubefix.innertube._cache_dir = cache_dir
        pytubefix.innertube._token_file = os.path.join(cache_dir, 'tokens.json')
    except ImportError:
        print("[X] pytubefix is not installed. Run: pip install pytubefix")
        sys.exit(1)

    print("We will now attempt to generate an OAuth2 token using pytubefix.")
    print("You will be provided a link and a code.")
    print("1. Open the link in your browser (make sure you are logged into YouTube).")
    print("2. Enter the code provided.")
    print("3. Authorize the application.\n")
    print("Waiting for you to authorize...")

    try:
        # This will block and prompt the user to authorize via the device flow
        yt = YouTube('https://www.youtube.com/watch?v=dQw4w9WgXcQ', use_oauth=True, allow_oauth_cache=True)
        # Force a fetch to ensure auth goes through completely
        _ = yt.title
    except Exception as e:
        print(f"\n[X] Failed to generate token: {e}")
        sys.exit(1)

    print("\n[OK] Authorization successful!")

    # Locate the tokens.json file generated by pytubefix
    cache_dir = os.path.join(os.path.abspath(os.path.dirname(__file__)), 'bot_temp', 'pytubefix_cache')
    token_file = os.path.join(cache_dir, 'tokens.json')

    if not os.path.exists(token_file):
        print(f"\n[X] Token file not found at expected location: {token_file}")
        sys.exit(1)

    with open(token_file, 'r', encoding='utf-8') as f:
        token_data = f.read()

    # Validate that it's actually valid JSON
    try:
        json.loads(token_data)
    except json.JSONDecodeError:
        print(f"\n[X] Token file contains invalid JSON data.")
        sys.exit(1)

    # Base64 encode the token string
    encoded_token = base64.b64encode(token_data.encode('utf-8')).decode('utf-8')

    env_line = f'YT_OAUTH2_TOKEN={encoded_token}\n'

    # Auto-update .env file
    env_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '.env')
    updated = False

    if os.path.exists(env_path):
        with open(env_path, 'r', encoding='utf-8') as f:
            lines = f.readlines()

        new_lines = []
        for line in lines:
            if line.startswith('YT_OAUTH2_TOKEN='):
                new_lines.append(env_line)
                updated = True
            else:
                new_lines.append(line)

        if not updated:
            if new_lines and not new_lines[-1].endswith('\n'):
                new_lines.append('\n')
            new_lines.append(env_line)
            updated = True

        with open(env_path, 'w', encoding='utf-8') as f:
            f.writelines(new_lines)
    else:
        with open(env_path, 'w', encoding='utf-8') as f:
            f.write(env_line)
        updated = True

    print("\n[OK] OAuth2 token generated and encoded successfully!")
    if updated:
        print(f"[OK] .env updated automatically: YT_OAUTH2_TOKEN set ({len(encoded_token):,} chars)")

    print("\n" + "=" * 65)
    print("  DONE — What to do next:")
    print("=" * 65 + "\n")
    print("  Local bot:  Restart the bot — it will load the new token from .env")
    print("  Render:     Go to dashboard.render.com -> your service ->")
    print("              Environment -> find YT_OAUTH2_TOKEN -> paste the following:\n")
    print(encoded_token)
    print("\n              -> Save Changes (Render auto-redeploys)")
    print("-" * 65)


if __name__ == '__main__':
    main()
